#!/bin/bash

export PATH=/sbin:/usr/sbin:/bin:/usr/bin
#加载相关模块

## 允许本地回路?Loopback - Allow unlimited traffic
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

## 防止SYN洪水?SYN-Flooding Protection
#iptables -N syn-flood
#iptables -A INPUT -i eth1 -p tcp --syn -j syn-flood
#iptables -A syn-flood -m limit --limit 1/s --limit-burst 4 -j RETURN
#iptables -A syn-flood -j DROP

## 确保新连接是设置了SYN标记的包?Make sure that new TCP connections are SYN packets 
#iptables -A INPUT -i eth0 -p tcp ! --syn -m state --state NEW -j DROP
## 允许HTTP的规则
iptables -A INPUT -i eth1 -p tcp -s 0/0 --sport 80 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i eth1 -p tcp -s 0/0 --sport 443 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i eth1 -p tcp -d 0/0 --dport 80 -j ACCEPT
iptables -A INPUT -i eth1 -p tcp -d 0/0 --dport 443 -j ACCEPT

## 允许DNS的规则
iptables -A INPUT -i eth1 -p udp -s 0/0 --sport 53 -m state --state ESTABLISHED -j ACCEPT
iptables -A INPUT -i eth1 -p udp -d 0/0 --dport 53 -j ACCEPT

iptables -A INPUT -i eth0 -p udp -s 0/0 --sport 53 -m state --state ESTABLISHED -j ACCEPT
iptables -A INPUT -i eth0 -p udp -d 0/0 --dport 53 -j ACCEPT


## IP包流量限制?IP packets limit
#iptables -A INPUT -f -m limit --limit 100/s --limit-burst 100 -j ACCEPT
#iptables -A INPUT -i eth0 -p icmp -j DROP

## 允许SSH
iptables -A INPUT -p tcp  --dport 22 -j ACCEPT

## 允许ftp
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -p tcp --dport 21 -m state --state NEW -j ACCEPT

## 允许mysql
iptables -A INPUT -p tcp -m tcp --sport 3306 -j ACCEPT

## 允许snmp
iptables -A INPUT -i eth0 -p udp -s 60.195.252.107 --dport 161 -j ACCEPT
iptables -A INPUT -i eth0 -p udp -s 60.195.252.110 --dport 161 -j ACCEPT

iptables -A INPUT -i eth1 -p udp -s 60.195.252.107 --dport 161 -j ACCEPT
iptables -A INPUT -i eth1 -p udp -s 60.195.252.110 --dport 161 -j ACCEPT

## ntp
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT
iptables -A INPUT -p udp --sport 123 -j ACCEPT

iptables -A INPUT -p tcp -m tcp --sport 873 -j ACCEPT

## 其它情况不允许?Anything else not allowed
iptables -P INPUT DROP

